### ISSUE TITLE
Read Nodes with Path

### ISSUE THREAD

**Issue by plasoft-MarioMuellner** [Traeger-GmbH/opcuanet-samples#11]
Hello,

I want to read nodes with the nodepath like `Objects/DeviceSet/IMM_ENGEL_247005/MachineMESStatus/StandstillMessage/Message`

In the next Image i try to access the node with different ways. Attept 1,3 and 4 returns the expected value.(`Path2NodeID` is only a Helper function which browse through the path)
![grafik](https://github.com/Traeger-GmbH/opcuanet-samples/assets/11715612/ea442c7c-29fe-44cb-908b-00b4fd8ff943)

What is the correct way to use the paths instead of the identifier? Did i have to browse for the nodeids or should i import a nodelist.xml(the ids changes through the manufacturer)

![grafik](https://github.com/Traeger-GmbH/opcuanet-samples/assets/11715612/ff927e1c-e39f-4f29-835d-7ac5e9e33530)

thanks in advanced
atheos

**Comment by kpreisser** [comment]
Hi @atheosangel,

thanks for creating this issue.

For efficiently getting the NodeID from a NodePath (and NodeID that is used as starting point), instead of browsing through the node children, you can use the `OpcClient.TranslateNodePath()` method. This invokes the TranslateNodePath service which only needs a single request in order to translate the path into a NodeID.

For example:
```cs
var nodeId = client.TranslatePath(OpcObjectTypes.ObjectsFolder, "DeviceSet/IMM_ENGEL_247005/MachineMESStatus");
```

If you want to get multiple node IDs at the same time, you can also instead use the `OpcClient.TranslatePaths()` method:
```cs
var nodeIds = client.TranslatePaths(
    OpcObjectTypes.ObjectsFolder, 
    "DeviceSet/IMM_ENGEL_247005/MachineMESStatus",
    "DeviceSet/IMM_ENGEL_123456/MyOtherNode")
    .ToArray();
```

Here, you will get a `OpcNodeId[]` array back, where each entry contains the node ID for the corresponding node path.
