### ISSUE TITLE
Clarification of client reconnection event behaviour 

### ISSUE THREAD

**Issue by JojoEffect** [Traeger-GmbH/opcuanet-samples#12]
Hi all,

I found the following unit test failing due to multiple Asserts at the end of the test are not valid:

`[Fact]
public async Task ClientReconnectOnServerRestart()
{
    // Arrange
    var server = new OpcServer();

    var client = new OpcClient("opc.tcp://localhost:4840/")
    {
        ReconnectTimeout = 5,
        UseBreakDetection = true
    };

    var calledReconnecting = false;
    var calledReconnected = false;
    var calledConnecting = false;
    var calledConnected = false;
    var calledBreakDetected = false;
    var calledDisconnected = false;

    server.Start();
    client.Connect();

    client.Disconnected += (sender, args) => calledDisconnected = true;
    client.Reconnecting += (sender, args) => calledReconnecting = true;
    client.Reconnected += (sender, args) => calledReconnected = true;
    client.Connecting += (sender, args) => calledConnecting = true;
    client.Connected += (sender, args) => calledConnected = true;
    client.BreakDetected += (sender, args) => calledBreakDetected = true;

    using var tokenSource = new CancellationTokenSource(30000);
    CancellationToken cancellationToken = tokenSource.Token;

    // Assert
    Assert.Equal(OpcClientState.Connected, client.State);

    // Act
    server.Stop();

    server.Start();

    while (!cancellationToken.IsCancellationRequested)
    {
        await Task.Delay(10);

        if (calledReconnected)
        {
            break;
        }
    }

    // Assert
    Assert.False(cancellationToken.IsCancellationRequested);
    Assert.False(calledBreakDetected);
    Assert.False(calledConnected);
    Assert.False(calledConnecting);
    Assert.True(calledReconnecting);
    Assert.True(calledReconnected);
    Assert.False(calledDisconnected);
}`

The result looks as follows and in this case not as expected:

![image](https://github.com/Traeger-GmbH/opcuanet-samples/assets/33799886/bc026cfb-15a2-49fd-9b0a-ca8f2d3eba7e)

What I understand from the [docs](https://docs.traeger.de/en/software/sdk/opc-ua/net/development.usecases?s[]=reconnected#loss-of-connection) is that with `ReconnectTimeout = 0` the `BreakDetected` should fire and with `ReconnectTimeout > 0` the `Reconnecting` and `Reconnected` should fire.

Am I missing any conditions/docs or am I using the API the wrong way?

Thanks for help!

**Comment by kpreisser** [comment]
Hi @JojoEffect,
thanks for opening this issue!

Your understanding is right that when `ReconnectTimeout > 0` and the client loses connection to the server, the `Reconnecting` event is triggered, and the client automatically tries to establish a new connection to the server.

If the client is able to reconnect to the server, one of the following events will be raised:
- `Reconnected` will be raised if the session still exists at the server, and the client was able to reconnect to the existing session.
- `Connected` will be raised if the session no longer exists at the server, and the client has automatically created a new session.

In both cases, the client can be used again, and previously created subscriptions should still work. However, there are some differences:
- When `Reconnected` is raised, it means for subscriptions that you will get e.g. data changes that occured during the time while the client didn't have a connection to the server, because the session (and therefore the subscription) was still active at the server and collected data.
-  When `Connected` is raised, the client had to re-create subscriptions on the server, which means e.g. data changes that occured during the time while the client didn't have a connection to the server will be lost (you will only get changes that occured after the client has created a new session).

Additionally, if you called `OpcClient.RegisterNode()`, then in case of `Reconnected` the node IDs will still work, but in case of `Connected` they will probably no longer work and you have to call `OpcClient.RegisterNode()` again.

In your example, you are restarting the server, so after the client can reconnect, the previous session will no longer exist on the server, which is why in this case `Connected` is always raised instead of `Reconnected`.

However, you are right that the documentation is a bit outdated and doesn't describe this difference, as this behavior was introduced with OPC UA .NET SDK version **2.12.0.0**. Previously, the `Reconnected` event was raised in call cases after the `Reconnecting` event.
We will track this internally to update the documentation, so that it reflects the current behavior.

Thanks!
